# Site settings
title: LearningThings.
header-img: img/home-bg.png
email: armstrong.amberly@gmail.com
copyright_name: armstrongamberly
description: > # this means to ignore newlines until "baseurl:"
  my code blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  armstrongamberly
learn_profile: armstrongamberly
email_username: armstrong.amberly@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
